### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by abehbatre** [MindorksOpenSource/MVVM-Architecture-Android-Beginners#1]
Hi @amitshekhariitbhu , good sample btw, so easy to understand 
but can i got some **unitTest** example?

and 1 more, how to **combine multiple network request**

thankyou  👍

**Comment by amitshekhariitbhu** [comment]
As we have done some simplifications in this project for the Beginners level, so, we can improve this project to go to the Advanced level, a few of the things which we can improve are as follows:

- Implement Dependency Inject Framework - Dagger in the project.
- Make ApiService Singleton and reuse the same instance for all the features.
- Create base classes such as BaseActivity.
- Handle all the API errors at a single place in a better way.
- Create Interfaces for the classes wherever required.
- Take advantage of Android KTX - Kotlin Extensions.
- Write Unit-Test
- and so on.

We will plan a new project for that.
